version: '3.3'
services:
    mongo:
        ports:
            - '27017:27017'
        container_name: mongo-img
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=123456
        image: mongo